['.*: ^(?!.*_Ex.*$)P_Eve_Sword_Normal_(Light|Strong)Attack.*_Hit1$']
HitLevelResultTargetCommonEffect = '''=> {
  var hitStunTime = 0.3d
  val newArray = JsonNodeFactory.instance.arrayNode
  val value = v.currentOpt[String].get
  val array = toJsonNodeT[ArrayNode](value)
  for (i <- 0 until array.size) array.get(i).get("Alias").asText match {
    case "HitStun" => hitStunTime = array.get(i).get("Time").asDouble
    case _ => newArray.add(array.get(i))
  }
  newArray.add(toJsonNode(s"""{ "Alias": "HitStun", "Time": ${hitStunTime * 2} }"""))
  newArray.toString
}'''
