# ...                                                        # Game Original Value
[P_Eve_Sword_Normal_FinishAttack4_1] # Incursion IV - Scarlet Stinger: ☐, ☐, ☐, △, Hold △
FirstSkillActiveAlias = "M_Scarlet_Stinger_Cast1"
AttackDamageRate = 8
ShieldAttackDamageRate = 8
TargetFilterAlias = "M_Scarlet_Stinger_Target"

[P_Eve_Sword_Normal_StrongAttack7_1] # Onslaught IV - Scarlet Airspin: △, ☐, △, ☐, Hold △
FirstSkillActiveAlias = "M_Scarlet_Airspin_Cast1"
AttackDamageRate = 8
ShieldAttackDamageRate = 8
TargetFilterAlias = "M_Scarlet_Airspin_Target"

['.*: ^P_Eve_Sword_Beta_ChargeSlashCombo.*$'] # Infinite Slash + Scarlet Blink Combo: L1+△
AttackDamageRate = 9.0                                       # 2.0
FirstSkillActiveAlias = "M_Scarlet_BlinkCombo_Cast1"         # "P_Eve_Sword_Beta_ChargeSlashCombo1_1_Cast1"
TargetFilterAlias = "M_Scarlet_BlinkCombo_Target"            # "P_Eve_Sword_0500_180_500_Target"
ShieldAttackDamageRate = 9.0                                 # 1.0

['.*: ^P_Eve_Sword_Beta_ShieldBreak.*'] # Shield Break -> Scarlet Swing Fast + Area Combo-+: L1+X
AttackDamageRate = 9.5                                       # 9.5
FirstSkillActiveAlias = "M_Scarlet_SwingFast_Cast1"          # "P_Eve_Sword_Beta_ShieldBreak1_Ex_Cast1"
TargetFilterAlias = "M_Scarlet_SwingFast_Target"             # "P_Eve_Sword_0500_180_500_Target"
ShieldAttackDamageRate = 9.5                                 # 9.5

[P_Eve_Tachy_Skill_ChainStab1_1] # Tachy Mode L1+☐
FirstSkillActiveAlias = "M_Scarlet_SwingTriple_Cast1"        # "P_Eve_Tachy_Skill_Chainstab1_1_Cast1"
TargetFilterAlias = "M_Scarlet_SwingTriple_Target"           # "P_Eve_Sword_0500_180_500_Target"

[P_Eve_Tachy_Skill_ScrewAttack1_1] # Tachy Mode L1+△
FirstSkillActiveAlias = "M_Scarlet_Swing_Cast1"              # "P_Eve_Tachy_Skill_ScrewAttack1_1_Cast1"
TargetFilterAlias = "M_Scarlet_Swing_Target"                 # "P_Eve_Tachy_Normal_0500_180_Target"

[P_Eve_Tachy_Skill_SwordAura1_1] # Tachy Mode L1+◯
FirstSkillActiveAlias = "M_Scarlet_JumpStampSlash_Cast1"     # "P_Eve_Tachy_Skill_SwordAura1_1_Cast1"
TargetFilterAlias = "M_Scarlet_JumpStampSlash_Target"        # "P_Eve_Tachy_Skill_SwordAura_Target"

[P_Eve_Tachy_Start2_1] # Tachy Mode -> Scarlet 1 Hit Super Attack
FirstSkillActiveAlias = "M_Scarlet_PhaseChange1_EndShieldOwn_Cast1"    # "P_Eve_Tachy_Start2_Cast1"
AttackDamageRate = 25                                        # 50
ShieldAttackDamageRate = 25                                  # 50
TargetFilterAlias = "M_Scarlet_HitArea"                      # "P_Eve_Tachy_Start2_1_Target"
