[N_Drone_Scan]                                               # based on https://www.nexusmods.com/stellarblade/mods/802
LifeTime = 30.0

['.*: ^P_Eve_SkillTree_Just(.*BetaGauge|.*BurstGauge).*$']
CalculationMultipleValue = '''=> v.objName match {
  case "P_Eve_SkillTree_JustParry_BetaGauge1" => 8
  case "P_Eve_SkillTree_JustParry_BetaGauge2" => 6
  case "P_Eve_SkillTree_JustEvade_BurstGauge1" => 4
  case "P_Eve_SkillTree_JustEvade_BurstGauge2" => 3
}'''
OverlapCount = 1
LifeTime = 11
StartDelayTime = 1
LoopIntervalTime = 1
ActiveTargetFilterAlias = 'Self'
LoopTargetFilterAlias = 'Self'

['.*: ^Gear_(?!.*_HitDmgUp).*$']                             # or, [ '=> v.startsWith("Gear_") && !v.contains("_HitDmgUp")' ]
CalculationMultipleValue = 2

['.*: ^Gear_.*_HitDmgUp.*$']
CalculationMultipleValue = 0.5

['.*: ^(P_Protector.*|SkillDamage_EveRangeCrowd.*)$']
CalculationMultipleValue = '''=>
  val orig = v.orig[Double]
  if (orig == 0) 0 else 2
''' 

[LV_Dead_Ocean]
ActionValue1 = ""                                            # "DeadZoneAlert"
LifeTime = -1                                                # 5
LifeType = "EffectLifeType_Infinite"                         # "EffectLifeType_IndependentTime"