# ...                                                        # Old Value
[P_Eve_Tachy_Start1_1]
AttackDamageRate = 0                                         # 0
Cancelable = false                                           # false
FirstActiveStepByEffect = "[{\"Effect\":\"P_Eve_TachyFusionModeItem\", \"SkillActiveStepAlias\":\"P_Eve_TachyFusion_Start1_Cast1\"}]"    # "[{\"Effect\":\"P_Eve_TachyFusionModeItem\", \"SkillActiveStepAlias\":\"P_Eve_TachyFusion_Start1_Cast1\"}]"
FirstSkillActiveAlias = "P_Eve_Tachy_Start1_Cast1"           # "P_Eve_Tachy_Start1_Cast1"
ShieldAttackDamageRate = 0                                   # 0
SkillType = "SkillType_None"                                 # "SkillType_None"
TargetDeadType = "None"                                      # "None"
TargetFilterAlias = "P_Eve_Tachy_Start1_1_Target"            # "P_Eve_Tachy_Start1_1_Target"
WorldObjectHitShow = ""                                      # ""

[P_Eve_Sword_JustParry_LightAttackCombo2_1] # Counter Chain I - Scarlet Judgement Cut, ☐, △, △+◯
AttackDamageRate = 12                                        # 10.4
FirstSkillActiveAlias = "P_Eve_Tachy_Start2_Cast1"           # "P_Eve_Tachy_Start1_Cast1"
ShieldAttackDamageRate = 12                                  # 10.4
TargetFilterAlias = "P_Eve_Tachy_Start2_1_Target"            # "P_Eve_Tachy_Start1_1_Target"
