#!/usr/bin/env bash
SCRIPT_PATH="${BASH_SOURCE}"
while [ -L "${SCRIPT_PATH}" ]; do
  SCRIPT_DIR="$(cd -P "$(dirname "${SCRIPT_PATH}")" > /dev/null 2>&1 && pwd)"
  SCRIPT_PATH="$(readlink "${SCRIPT_PATH}")"
  [[ ${SCRIPT_PATH} != /* ]] && SCRIPT_PATH="${SCRIPT_DIR}/${SCRIPT_PATH}"
done
SCRIPT_PATH="$(readlink -f "${SCRIPT_PATH}")"
SCRIPT_DIR="$(cd -P "$(dirname -- "${SCRIPT_PATH}")" > /dev/null 2>&1 && pwd)"
if [ ! -f "${SCRIPT_PATH}/lib/luaj-jse-1.0.0.jar" ]; then
  mkdir -p "${SCRIPT_DIR}/lib"
  curl -JLso "${SCRIPT_DIR}/lib/luaj-jse-1.0.0.jar" https://github.com/jpabscale/luaj/releases/download/1.0.0/luaj-jse-1.0.0.jar
fi
SERVER=--server=true
if [ "$1" == "-s" ]; then
  SERVER=--server=false
fi
scala-cli --suppress-outdated-dependency-warning $SERVER "$SCRIPT_DIR/project.scala" -- $*
