//> using repository https://repo1.maven.org/maven2
//> using repository https://jitpack.io
//> using jvm zulu:25.0.4
//> using javaOptions --enable-native-access=ALL-UNNAMED --sun-misc-unsafe-memory-access=allow -Dpolyglot.engine.WarnInterpreterOnly=false
//> using scala 2.13.18
//> using options --deprecation -feature -language:implicitConversions
//> using dep com.fasterxml.jackson.core:jackson-databind:2.22.1
//> using dep com.fasterxml.jackson.dataformat:jackson-dataformat-toml:2.22.1
//> using jar lib/luaj-jse-1.0.0.jar
//> using dep com.jayway.jsonpath:json-path:3.0.0
//> using dep org.apache.bcel:bcel:6.12.0
//> using dep org.graalvm.polyglot:js:25.2.4,type=pom
//> using dep org.graalvm.polyglot:polyglot:25.2.4
//> using dep org.graalvm.polyglot:python:25.2.4,type=pom
//> using dep com.lihaoyi::os-lib:0.11.8
//> using dep com.lihaoyi::sourcecode:0.4.4
//> using dep org.scala-lang:scala-compiler:2.13.18
//> using dep org.scala-lang:scala-reflect:2.13.18
//> using dep org.jetbrains.kotlin:kotlin-compiler-embeddable:2.4.10
//> using dep org.jetbrains.kotlin:kotlin-stdlib:2.4.10
//> using dep org.scala-lang.modules::scala-parallel-collections:1.2.0
//> using dep org.slf4j:slf4j-nop:2.0.18
//> using dep com.github.jpabscale:uasset4j:33ef77e.e9f24e0
//> using file automod.sc
//> using file patchCustom.sc
//> using file patchlet.sc
//> using file uassetapi.sc
//> using file unityapi.sc
//> using file unitymod.sc
//> using file kotlinapi.sc
//> using mainClass automod
//> using dep com.github.jpabscale:asset4j:9aa8c6e.1
