# ...                                                        # Game Original Value
[P_Eve_Sword_Normal_LightAttack4_1_Ex] # Incursion N β - Counter Chain I - ☐, ☐, Hold ☐
AttackDamageRate = 10.4                                      # 2.7
FirstSkillActiveAlias = "P_Eve_Sword_JustParry_LightAttackCombo2_1_Cast1"    # "P_Eve_Sword_Normal_LightAttack4_1_Ex_Cast1"
TargetFilterAlias = "P_Eve_Sword_0500_180_500_Target"        # "P_Eve_Sword_0500_180_500_Target"
ShieldAttackDamageRate = 10.4                                # 1.4

[P_Eve_Sword_Normal_LightAttackChain1_1] # Incursion III β - Shield Break: ☐, △, Hold ☐
AttackDamageRate = 9.5                                       # 2.3
FirstSkillActiveAlias = "P_Eve_Sword_Beta_ShieldBreak1_Ex_Cast1"    # "P_Eve_Sword_Normal_LightAttackChain1_1_Cast"
TargetFilterAlias = "P_Eve_Sword_0500_180_500_Target"        # "P_Eve_Sword_0500_180_500_Target"
ShieldAttackDamageRate = 9.5                                 # 1.2

[P_Eve_Sword_Normal_FinishAttack4_1_Ex] # Incursion IV β - Tachy Judgement Wave: ☐, ☐, ☐, △, Hold △
AttackDamageRate = 6                                         # 5.7
FirstSkillActiveAlias = "P_Eve_Tachy_Skill_SwordAura1_1_Cast1"    # "P_Eve_Sword_Normal_FinishAttack4_1_Ex_Cast1"
TargetFilterAlias = "P_Eve_Tachy_Skill_SwordAura_Target"     # "P_Eve_Sword_0500_180_500_Target"
ShieldAttackDamageRate = 6                                   # 2.9

[P_Eve_Sword_Normal_StrongAttack10_1_Ex] # Incursion I β - Punishing Edge: ☐, △, △, Hold △
AttackDamageRate = 8                                         # 6.0
FirstSkillActiveAlias = "P_Eve_Sword_Burst_FinishAttack1_1_Cast1"    # "P_Eve_Sword_Normal_StrongAttack10_1_Ex_Cast1"
TargetFilterAlias = "P_Eve_Sword_0500_360_500_Target"        # "P_Eve_Sword_0500_180_500_Target"
ShieldAttackDamageRate = 8                                   # 3.0

[P_Eve_Sword_Normal_StrongAttack5_1_Ex] # Onslaught I β - Triplet: △, △, Hold △
AttackDamageRate = 4                                         # 4.5
FirstSkillActiveAlias = "P_Eve_Sword_Beta_ChainStabCombo1_Ex_Cast1"    # "P_Eve_Sword_Normal_StrongAttack5_1_Ex_Cast1"
TargetFilterAlias = "P_Eve_Sword_0500_180_500_Target"        # "P_Eve_Sword_0500_180_500_Target"
ShieldAttackDamageRate = 2                                   # 2.3

[P_Eve_Sword_Normal_StrongAttack8_1_Ex] # Onslaught II β - Tachy Jugdgement Rave: △, ☐, ☐, Hold △
AttackDamageRate = 6                                         # 4.6
FirstSkillActiveAlias = "P_Eve_Tachy_Skill_Chainstab1_1_Cast1"    # "P_Eve_Sword_Normal_StrongAttack8_1_Ex_Cast1"
TargetFilterAlias = "P_Eve_Sword_0500_180_500_Target"        # "P_Eve_Sword_0500_180_500_Target"
ShieldAttackDamageRate = 6                                   # 2.3

[P_Eve_Sword_Normal_StrongAttack6_1_Ex] # Onslaught III β - Slash: △, ☐, Hold ☐, Hold △
AttackDamageRate = 10                                        # 4.1
FirstSkillActiveAlias = "P_Eve_Sword_Beta_ChargeSlashCombo1_Ex_Cast1"    # "P_Eve_Sword_Normal_StrongAttack6_1_Ex_Cast1"
TargetFilterAlias = "P_Eve_Tachy_Skill_SwordAura_Target"     # "P_Eve_Sword_0500_180_500_Target"
ShieldAttackDamageRate = 4                                   # 2.1

[P_Eve_Sword_Normal_StrongAttack7_1_Ex] # Onslaught IV β - Descending Break: △, ☐, △, ☐, Hold △
AttackDamageRate = 8                                         # 5.1
FirstSkillActiveAlias = "P_Eve_Sword_Burst_SpinAttack1_1_Cast1"    # "P_Eve_Sword_Normal_StrongAttack7_1_Ex_Cast1"
TargetFilterAlias = "P_Eve_Sword_0600_360_500_Target"        # "P_Eve_Sword_0800_180_500_Target"
ShieldAttackDamageRate = 8                                   # 2.6

[P_Eve_Sword_JustParry_LightAttackCombo2_1] # Counter Chain I - Tempest: Perfect Parry, ☐, △, △+◯
AttackDamageRate = 12                                        # 10.4
FirstSkillActiveAlias = "P_Eve_Sword_Burst_MassiveAttack1_1_Cast1"    # "P_Eve_Sword_JustParry_LightAttackCombo2_1_Cast1"
TargetFilterAlias = "P_Eve_Sword_0800_360_500_Target"        # "P_Eve_Sword_0500_180_500_Target"
ShieldAttackDamageRate = 12                                  # 10.4

[P_Eve_Sword_Normal_FinishAttack3_4_Ex] # ???
AttackDamageRate = 8                                         # 5.0
FirstSkillActiveAlias = "P_Eve_Sword_Beta_ChainStab1_1_Cast1"    # "P_Eve_Sword_Normal_FinishAttack3_4_Cast1"
TargetFilterAlias = "P_Eve_Sword_0500_180_500_Target"        # "P_Eve_Sword_0500_180_500_Target"
ShieldAttackDamageRate = 4                                   # 2.5

['.*: ^P_Eve_Sword_Air_GuardBreakAttack1_1.*'] # Tachy Air Nosedive: [Hold] △
AttackDamageRate = 6                                         # 2
FirstSkillActiveAlias = "P_Eve_Tachy_Air_StrongAttack1_1_Cast1"    # "P_Eve_Sword_Air_GuardBreakAttack1_1_Cast1"
ShieldAttackDamageRate = 6                                   # 2.4

[P_Eve_Sword_Air_LightAttack1_1] # Tachy Air Interception ending with Tachy Blade Fury: while on air...  ☐, ☐, ☐, ☐
AttackDamageRate = 2                                         # 1.4
FirstSkillActiveAlias = "P_Eve_Tachy_Air_LightAttack1_1_Cast1"    # "P_Eve_Sword_Air_LightAttack1_1_Cast1"
ShieldAttackDamageRate = 2                                   # 0.7

[P_Eve_Sword_Air_LightAttack2_1]
AttackDamageRate = 2                                         # 1.5
FirstSkillActiveAlias = "P_Eve_Tachy_Air_LightAttack2_1_Cast1"    # "P_Eve_Sword_Air_LightAttack2_1_Cast1"
ShieldAttackDamageRate = 2                                   # 0.7

[P_Eve_Sword_Air_LightAttack3_1]
AttackDamageRate = 2                                         # 1.8
FirstSkillActiveAlias = "P_Eve_Tachy_Air_LightAttack3_1_Cast1"    # "P_Eve_Sword_Air_LightAttack3_1_Cast1"
ShieldAttackDamageRate = 2                                   # 0.9

[P_Eve_Sword_Air_LightAttack4_1]
AttackDamageRate = 6                                         # 2.2
FirstSkillActiveAlias = "P_Eve_Tachy_Skill_ScrewAttack1_1_Cast1"    # "P_Eve_Sword_Air_LightAttack4_1_Cast1"
ShieldAttackDamageRate = 6                                   # 1.1

['.*: ^P_Eve_Sword_Normal_DashAttack[^C].*'] # Tachy Judgement Rush: Hold △, △, △
AttackDamageRate = 3                                         # 1.7
FirstSkillActiveAlias = "P_Eve_Tachy_Normal_DashAttack1_1_Cast1"    # "P_Eve_Sword_Normal_DashAttack1_1_Cast1"
ShieldAttackDamageRate = 3                                   # 0.9

['.*: ^P_Eve_Sword_Normal_DashAttackCombo1_1.*']
AttackDamageRate = 3                                         # 4.0
FirstSkillActiveAlias = "P_Eve_Tachy_Normal_DashAttackCombo1_1_Cast1"    # "P_Eve_Sword_Normal_DashAttackCombo1_1_Cast1"
ShieldAttackDamageRate = 3                                   # 2.0

['.*: ^P_Eve_Sword_Normal_Guard[1-2]_1$'] # Tachy Guard: L1
FirstSkillActiveAlias = "P_Eve_Tachy_Normal_Guard1_1_Parry1"
TargetFilterAlias = "P_Eve_Tachy_Normal_Guard1_1_Target"

['.*: ^P_Eve_Sword_Burst_SpinAttack[1-2]_1$'] # Descending Break -> Ex Combo I + Scarlet Move Back Shot II/Fusion Blade Fury: R1+☐
FirstSkillActiveAlias = "P_Eve_Sword_Normal_FinishAttack4_1_Ex_Cast1"    # "P_Eve_Sword_Burst_SpinAttack1_1_Cast1"
AttackDamageRate = 8                                         # 8
TargetFilterAlias = "P_Eve_Sword_0500_180_500_Target"        # "P_Eve_Sword_0600_360_500_Target"
ShieldAttackDamageRate = 8                                   # 8

['.*: ^P_Eve_Sword_Burst_FinishAttack[1-3]_1$'] # Punishing Edge -> Ex Combo II + Scarlet Back Dash Cut/Fusion Judgement Rave: R1+△
FirstSkillActiveAlias = "P_Eve_Sword_Normal_DashAttackCombo1_1_Ex_Cast1"    # "P_Eve_Sword_Burst_FinishAttack1_1_Cast1"
AttackDamageRate = 8                                         # 8
TargetFilterAlias = "P_Eve_Sword_0500_180_500_Target"        # "P_Eve_Sword_0500_360_500_Target"
ShieldAttackDamageRate = 8                                   # 8

[P_Eve_Sword_Burst_MeleeCombatBuff1_1] # Overdrive -> Ex Combo III + Scarlet Air Dash Space Cut/Fusion Judgement Wave: R1+X
AttackDamageRate = 8                                         # 3.0
FirstSkillActiveAlias = "P_Eve_Sword_Normal_LightAttack4_1_Ex_Cast1"    # "P_Eve_Sword_Burst_MeleeCombatBuff1_1_Cast1"
ShieldAttackDamageRate = 12                                  # 3.0
TargetFilterAlias = "P_Eve_Sword_0500_180_500_Target"        # "P_Eve_Sword_0500_180_500_Target"

[P_Eve_Tachy_Start2_1]
TargetFilterAlias = "P_Eve_Tachy_Start2_1_Target"            # "P_Eve_Tachy_Start2_1_Target"

[P_Eve_Tachy_Start1_1] # Tachy Mode: L3+R3
AttackDamageRate = 0                                         # 0
Cancelable = false                                           # false
FirstActiveStepByEffect = "[{\"Effect\":\"P_Eve_TachyFusionModeItem\", \"SkillActiveStepAlias\":\"P_Eve_TachyFusion_Start1_Cast1\"}]"    # "[{\"Effect\":\"P_Eve_TachyFusionModeItem\", \"SkillActiveStepAlias\":\"P_Eve_TachyFusion_Start1_Cast1\"}]"
FirstSkillActiveAlias = "P_Eve_Tachy_Start1_Cast1"           # "P_Eve_Tachy_Start1_Cast1"
ShieldAttackDamageRate = 0                                   # 0
SkillType = "SkillType_None"                                 # "SkillType_None"
TargetDeadType = "None"                                      # "None"
TargetFilterAlias = "P_Eve_Tachy_Start1_1_Target"            # "P_Eve_Tachy_Start1_1_Target"
WorldObjectHitShow = ""                                      # ""
