# based on https://www.nexusmods.com/stellarblade/mods/1156

['=> Multiply HP/SP on objects 17-32 and 301-327 by 6, and object 324 & 327 to 420/420.']
'=>' = '''{
  v.toIntOption match {
    case Some(n) => (17 <= n && n <= 32) | (301 <= n && n <= 327)
    case _ => false 
  }
}'''
StatValue4 = '=> if (v.objName == "324" | v.objName == "327") 420 else v.orig[Double] * 6'
StatValue5 = '=> if (v.objName == "324" | v.objName == "327") 420 else v.orig[Double] * 6'

