[N_Drone_Normal_Scan1_1]
CoolTime = 4

[P_Eve_Fusion_Lockon_Evade1_1]
JustActionTime = 1
JustActionTime_StoryMode = 1

[P_Eve_Fusion_Normal_Evade1_1]
JustActionTime = 1
JustActionTime_StoryMode = 1

[P_Eve_Fusion_Normal_Guard1_1]
CoolTime = 0.1
JustActionTime = 1
JustActionTime_StoryMode = 1

[P_Eve_Sword_Air_GuardBreakAttack1_1]
FirstSkillActiveAlias = "P_Eve_Tachy_Air_StrongAttack1_1_Cast1"

[P_Eve_Sword_Air_GuardBreakAttack1_1_Ex]
FirstSkillActiveAlias = "P_Eve_Fusion_Air_StrongAttack1_1_Cast1"

[P_Eve_Sword_Air_LightAttack1_1]
FirstSkillActiveAlias = "P_Eve_Tachy_Air_LightAttack1_1_Cast1"

[P_Eve_Sword_Air_LightAttack2_1]
FirstSkillActiveAlias = "P_Eve_Tachy_Air_LightAttack2_1_Cast1"

[P_Eve_Sword_Air_LightAttack3_1]
FirstSkillActiveAlias = "P_Eve_Tachy_Air_LightAttack3_1_Cast1"

[P_Eve_Sword_Air_LightAttack4_1]
FirstSkillActiveAlias = "P_Eve_Tachy_Skill_ScrewAttack1_1_Cast1"

[P_Eve_Sword_Beta_ChainStab1Ex]
StartDelayTick = 5

[P_Eve_Sword_Beta_ChainStab1_1]
HitLevel = 3
StartDelayTick = 5

[P_Eve_Sword_Beta_ChainStabCombo1Ex]
AttackDamageRate = 15
FirstSkillActiveAlias = "M_Scarlet_BlinkCut_Cast1"
ShieldAttackDamageRate = 8
StartDelayTick = 5

[P_Eve_Sword_Beta_ChainStabCombo1_1]
AttackDamageRate = 9
FirstSkillActiveAlias = "M_Scarlet_BlinkCut_Cast1"
ShieldAttackDamageRate = 5
StartDelayTick = 5

[P_Eve_Sword_Beta_ChargeSlash1Ex]
StartDelayTick = 5

[P_Eve_Sword_Beta_ChargeSlash1_1]
HitLevel = 3
StartDelayTick = 5

[P_Eve_Sword_Beta_ChargeSlash2_1]
StartDelayTick = 5

[P_Eve_Sword_Beta_ChargeSlashCombo1Ex_1]
AttackDamageRate = 10
FirstSkillActiveAlias = "M_Scarlet_AirDashSpaceCut_Cast1"
ShieldAttackDamageRate = 8
StartDelayTick = 5

[P_Eve_Sword_Beta_ChargeSlashCombo1_1]
AttackDamageRate = 10
FirstSkillActiveAlias = "M_Scarlet_SwingCombo_Cast1"
ShieldAttackDamageRate = 10
StartDelayTick = 5

[P_Eve_Sword_Beta_ShieldBreak1Ex_1]
AttackDamageRate = 15
FirstSkillActiveAlias = "M_Scarlet_MoveBackShot2_Cast1"
ShieldAttackDamageRate = 8
StartDelayTick = 5

[P_Eve_Sword_Beta_ShieldBreak1_1]
ShieldAttackDamageRate = 5
StartDelayTick = 5

[P_Eve_Sword_Beta_ShieldBreak2_1]
ShieldAttackDamageRate = 5
StartDelayTick = 5

[P_Eve_Sword_Beta_SwordAura1Ex_1]
SkillType = "SkillType_MeleeAttack"
StartDelayTick = 5

[P_Eve_Sword_Beta_SwordAura1_1]
ActiveSkillWhileCutoff = false
Cancelable = false
HitLevel = 3
SkillType = "SkillType_MeleeAttack"
StartDelayTick = 5

[P_Eve_Sword_Beta_SwordAuraCombo1Ex_1]
AttackDamageRate = 15
FirstSkillActiveAlias = "M_Scarlet_BlinkShot_Cast1"
ShieldAttackDamageRate = 8
StartDelayTick = 5

[P_Eve_Sword_Beta_SwordAuraCombo1_1]
AttackDamageRate = 9
FirstSkillActiveAlias = "M_Scarlet_BlinkShot_Cast1"
ShieldAttackDamageRate = 5
StartDelayTick = 5

[P_Eve_Sword_Burst_FinishAttack1_1]
AttackDamageRate = 15
FirstSkillActiveAlias = "M_Scarlet_BackDashSpaceCut_Cast1"
ShieldAttackDamageRate = 10

[P_Eve_Sword_Burst_FinishAttack2_1]
AttackDamageRate = 15
FirstSkillActiveAlias = "M_Scarlet_BackDashSpaceCut_Cast1"
ShieldAttackDamageRate = 10

[P_Eve_Sword_Burst_FinishAttack3_1]
AttackDamageRate = 15
FirstSkillActiveAlias = "M_Scarlet_BackDashSpaceCut_Cast1"
ShieldAttackDamageRate = 10

[P_Eve_Sword_Burst_SpinAttack1_1]
AttackDamageRate = 50
FirstSkillActiveAlias = "P_Eve_Sword_Burst_SpinAttack1_1_Cast1"
ShieldAttackDamageRate = 50

[P_Eve_Sword_Burst_SpinAttack2_1]
AttackDamageRate = 50
FirstSkillActiveAlias = "P_Eve_Sword_Burst_SpinAttack2_1_Cast1"
ShieldAttackDamageRate = 50

[P_Eve_Sword_Evade_Evade1_1]
CoolTime = 0.1

[P_Eve_Sword_LockonEvade_Evade1_1]
CoolTime = 0.1

[P_Eve_Sword_Lockon_Evade1_1]
CoolTime = 0.1

[P_Eve_Sword_Lockon_Evade2_1]
CoolTime = 0.1
JustActionTime = 1
JustActionTime_StoryMode = 1

[P_Eve_Sword_Normal_DashAttack1_1]
CoolTime = 1
FirstSkillActiveAlias = "P_Eve_Tachy_Normal_DashAttack1_1_Cast1"

[P_Eve_Sword_Normal_DashAttack1_2]
FirstSkillActiveAlias = "P_Eve_Tachy_Normal_DashAttack1_1_Cast1"

[P_Eve_Sword_Normal_DashAttack1_2_Ex]
FirstSkillActiveAlias = "P_Eve_Fusion_Normal_DashAttack1_1_Cast1"

[P_Eve_Sword_Normal_DashAttack2_1]
FirstSkillActiveAlias = "P_Eve_Tachy_Normal_DashAttack1_1_Cast1"

[P_Eve_Sword_Normal_DashAttack3_1]
CoolTime = 1
FirstSkillActiveAlias = "P_Eve_Tachy_Normal_DashAttack1_1_Cast1"

[P_Eve_Sword_Normal_DashAttack4_1]
CoolTime = 1
FirstSkillActiveAlias = "P_Eve_Tachy_Normal_DashAttack1_1_Cast1"

[P_Eve_Sword_Normal_DashAttackCombo1_1]
FirstSkillActiveAlias = "P_Eve_Tachy_Normal_DashAttackCombo1_1_Cast1"

[P_Eve_Sword_Normal_DashAttackCombo1_1_Ex]
FirstSkillActiveAlias = "P_Eve_Fusion_Normal_DashAttackCombo1_1_Cast1"

[P_Eve_Sword_Normal_DashAttackCombo2_1]
FirstSkillActiveAlias = "P_Eve_Tachy_Normal_DashAttackCombo1_1_Cast1"

[P_Eve_Sword_Normal_Evade1_1]
CoolTime = 0.1

[P_Eve_Sword_Normal_Evade2_1]
CoolTime = 0.1
JustActionTime = 1
JustActionTime_StoryMode = 1

[P_Eve_Sword_Normal_Guard1_1]
CoolTime = 0.1

[P_Eve_Sword_Normal_Guard2_1]
CoolTime = 0.1
JustActionTime = 1
JustActionTime_StoryMode = 1

[P_Eve_Tachy_Lockon_Evade1_1]
JustActionTime = 1
JustActionTime_StoryMode = 1

[P_Eve_Tachy_Normal_Evade1_1]
JustActionTime = 1
JustActionTime_StoryMode = 1

[P_Eve_Tachy_Normal_Guard1_1]
CoolTime = 0.1
JustActionTime = 1
JustActionTime_StoryMode = 1

[P_Eve_Tachy_Start1_1]
AttackDamageRate = 50
Cancelable = true
FirstActiveStepByEffect = ""
FirstSkillActiveAlias = "P_Eve_Tachy_Start2_Cast1"
ShieldAttackDamageRate = 50
SkillType = "SkillType_MeleeAttack"
TargetDeadType = "Step2"
TargetFilterAlias = "P_Eve_Tachy_Start2_1_Target"
WorldObjectHitShow = "Hit/Result_Hit_Env"

[P_Eve_Tachy_Start2_1]
TargetFilterAlias = "P_Eve_Tachy_Start2_1_Target"

