[BS_Nier_01]
SoundEventAlias = "NIER_OFF"

[BS_Nier_01_Dmg]
SoundEventAlias = "NIER_OFF"

[BS_Nier_02]
SoundEventAlias = "NIER_OFF"

[BS_Nier_03]
SoundEventAlias = "NIER_OFF"

[BS_Nier_04]
SoundEventAlias = "NIER_OFF"

