['.*: ^P_Eve_Sword_(Normal_(Light|Strong|Finish|DashAttackCombo)|Air_RollingAttack).*Ex_Hit.*$']
SkillAttackDamageRate = '=> v.orig[Double] * 0.2'
SkillShieldAttackDamageRate = '=> v.orig[Double] * 0.2'

['.*: ^P_Eve_Sword_Burst_MassiveAttack.*Hit.*']
SkillAttackDamageRate = '=> v.orig[Double]'
SkillShieldAttackDamageRate = '=> v.orig[Double]'

['.*: ^P_Eve_(Sword_Normal_DashAttack1_2_Ex|Fusion_JustParry_LightAttack1_1)_Hit1$']
SkillAttackDamageRate = '=> v.orig[Double] * 0.2'
SkillShieldAttackDamageRate = '=> v.orig[Double] * 0.2'
