['.*: ^Gear_(?!BetaCrystalAdditiveRate)(?!.*_HitDmgUp).*$']  # or, [ '=> v.startsWith("Gear_") && v.startsWith("Gear_BetaCrystalAdditiveRate") && !v.contains("_HitDmgUp")' ]
CalculationMultipleValue = 2

['.*: ^Gear_.*_HitDmgUp.*$']
CalculationMultipleValue = 0.5

['.*: ^(P_Protector.*|SkillDamage_EveRangeCrowd.*)$']
CalculationMultipleValue = '''=>
  val orig = v.orig[Double]
  if (orig == 0) 0 else 2
''' 

[P_Eve_SkillTree_TachyGaugeReduceConsumeRate]
CalculationValue = 0.8                                       # 0.2

[LV_Dead_Ocean]
ActionValue1 = ""                                            # "DeadZoneAlert"
LifeTime = -1                                                # 5
LifeType = "EffectLifeType_Infinite"                         # "EffectLifeType_IndependentTime"

[LV_Dead_DesertSandTrap]
Action1 = "EffectAction_None"                                # "EffectAction_ImmediateDeath"
ActorState1 = "ActorState_None"                              # "ActorState_BlockRevival"
LifeTime = -1                                                # 0.5
LifeType = "EffectLifeType_Infinite"                         # "EffectLifeType_IndependentTime"
ActiveTargetFilterAlias = "None"                             # "Self"

[P_Eve_Stance_GunGorgon]
ActorState1 = "ActorState_None"                              # "ESBActorState::ActorState_BlockRotation"

['.*: ^Gear_BetaCrystalAdditiveRate_.*$']
StatType = "ActorStatType_DrainHpByAttackPowerRate"          # "ESBActorStatType::ActorStatType_HP"
StatCalculationType = "EffectCalculationType_Static"         # "ESBEffectCalculationType::EffectCalculationType_HealStatic"
CalculationValue = '''=> {
  val prefix = "Gear_BetaCrystalAdditiveRate_"
  var n = 0.003 * v.objName(prefix.length).toDouble
  if (v.objName.contains("MK2")) n = n * 2
  n
}'''                                                         # 90.0
LifeType = "EffectLifeType_Infinite"                         # "ESBEffectLifeType::EffectLifeType_IndependentTime",
LifeTime = 0                                                 # 0.1
