# ...                                                        # Game Original Value
['.*: ^P_Eve_Sword_Beta_ChargeSlashCombo.*$'] # Slash + Blink Combo: L1+△
AttackDamageRate = 9.0                                       # 2.0
FirstSkillActiveAlias = "M_Scarlet_BlinkCombo_Cast1"         # "P_Eve_Sword_Beta_ChargeSlashCombo1_1_Cast1"
TargetFilterAlias = "M_Scarlet_BlinkCombo_Target"            # "P_Eve_Sword_0500_180_500_Target"
ShieldAttackDamageRate = 9.0                                 # 1.0

['.*: ^P_Eve_Sword_Burst_MassiveAttack[1-2]_1$'] # Tempest -> Scarlet Judgement Cut: R1+◯
AttackDamageRate = 12                                        # 12
FirstSkillActiveAlias = "P_Eve_Tachy_Start2_Cast1"           # "P_Eve_Sword_Burst_MassiveAttack1_1_Cast1"
ShieldAttackDamageRate = 12                                  # 12
TargetFilterAlias = "P_Eve_Tachy_Start2_1_Target"            # "P_Eve_Sword_0800_360_500_Target"

['.*: ^P_Eve_Sword_Beta_ShieldBreak.*$'] # Shield Break -> Overdrive + Scarlet 1 Hit ~KO~ Shield Breaker: L1+X
AttackDamageRate = 8.0                                       # 8.0
FirstSkillActiveAlias = "P_Eve_Sword_Burst_MeleeCombatBuff1_1_Cast1"    # "P_Eve_Sword_Beta_ShieldBreak2_1_Cast1"
TargetFilterAlias = "P_Eve_Sword_0500_180_500_Target"        # "P_Eve_Sword_0500_180_500_Target"
ShieldAttackDamageRate = 7.0                                 # 7.0
StartDelayTick = 1                                           # 1

