# ...                                                        # Game Original Value
[N_Drone_Normal_Scan1_1]
CoolTime = 4                                                 # 8

[P_Eve_Sword_Air_Evade1_1]
UsableCount = 1000                                           # 1

['.*: ^P_Eve_Tachy_Skill.*$']
AttackDamageRate = '=> v.orig[Double]'                       # 6.0
ShieldAttackDamageRate = '=> v.orig[Double]'                 # 6.0
