# ...                                                        # Game Original Value
[N_Drone_Normal_Scan1_1]
CoolTime = 4                                                 # 8

[P_Eve_Fusion_Lockon_Evade1_1]
JustActionTime = 1                                           # 0.2
JustActionTime_StoryMode = 1                                 # 0.3

[P_Eve_Fusion_Normal_Evade1_1]
JustActionTime = 1                                           # 0.2
JustActionTime_StoryMode = 1                                 # 0.3

[P_Eve_Fusion_Normal_Guard1_1]
CoolTime = 0.1                                               # 0.2
JustActionTime = 1                                           # 0.2
JustActionTime_StoryMode = 1                                 # 0.2

[P_Eve_Gun_ShootExplosiveSlug1_1]
CoolTime = 0                                                 # 0.8

[P_Eve_Gun_ShootScatterSlug1_1]
CoolTime = 0                                                 # 1

[P_Eve_Sword_Air_Evade1_1]
UsableCount = 1000                                           # 1

[P_Eve_Sword_Evade_Evade1_1]
CoolTime = 0.1                                               # 0.8

[P_Eve_Sword_LockonEvade_Evade1_1]
CoolTime = 0.1                                               # 0.8

[P_Eve_Sword_Lockon_Evade1_1]
CoolTime = 0.1                                               # 0.8

[P_Eve_Sword_Lockon_Evade2_1]
CoolTime = 0.1                                               # 0.8
JustActionTime = 1                                           # 0.15
JustActionTime_StoryMode = 1                                 # 0.3

[P_Eve_Sword_Normal_DashAttack1_1]
CoolTime = 1                                                 # 8

[P_Eve_Sword_Normal_DashAttack3_1]
CoolTime = 1                                                 # 8

[P_Eve_Sword_Normal_DashAttack4_1]
CoolTime = 1                                                 # 8

[P_Eve_Sword_Normal_Evade1_1]
CoolTime = 0.1                                               # 0.8

[P_Eve_Sword_Normal_Evade2_1]
CoolTime = 0.1                                               # 0.8
JustActionTime = 1                                           # 0.15
JustActionTime_StoryMode = 1                                 # 0.3

[P_Eve_Sword_Normal_Guard1_1]
CoolTime = 0.1                                               # 0.4

[P_Eve_Sword_Normal_Guard2_1]
CoolTime = 0.1                                               # 0.4
JustActionTime = 1                                           # 0.15
JustActionTime_StoryMode = 1                                 # 0.2

[P_Eve_Tachy_Lockon_Evade1_1]
JustActionTime = 1                                           # 0.2
JustActionTime_StoryMode = 1                                 # 0.3

[P_Eve_Tachy_Normal_Evade1_1]
JustActionTime = 1                                           # 0.2
JustActionTime_StoryMode = 1                                 # 0.3

[P_Eve_Tachy_Normal_Guard1_1]
CoolTime = 0.1                                               # 0.2
JustActionTime = 1                                           # 0.2
JustActionTime_StoryMode = 1                                 # 0.2

