# ...                                                        # Game Original Value
['.*: ^P_Eve_Sword_(Normal_StrongAttack(6|8)|Air_RollingAttack).*Ex_Finish1$']
NextStepAlias = '''=> v.objName match {
  case "P_Eve_Sword_Air_RollingAttack1_1_Ex_Finish1" => "P_Eve_Fusion_Skill_ScrewAttack1_1_Cast1"
  case "P_Eve_Sword_Normal_StrongAttack6_1_Ex_Finish1" => "P_Eve_Fusion_Skill_SwordAura1_1_Cast1"
  case "P_Eve_Sword_Normal_StrongAttack8_1_Ex_Finish1" => "P_Eve_Fusion_Skill_Chainstab1_1_Cast1"

  case _ => null
}'''                                                         # null

[P_Eve_Sword_Burst_MeleeCombatBuff1_1_Finish1]
NextStepAlias = "P_Eve_Sword_Burst_MassiveAttack1_1_Cast1"   # null
