# ...                                                        # Old Value
[P_Eve_Fusion_Lockon_Evade1_1]
JustActionTime = 1                                           # 0.2
JustActionTime_StoryMode = 1                                 # 0.3

[P_Eve_Fusion_Normal_Evade1_1]
JustActionTime = 1                                           # 0.2
JustActionTime_StoryMode = 1                                 # 0.3

[P_Eve_Fusion_Normal_Guard1_1]
CoolTime = 0.1                                               # 0.2
JustActionTime = 1                                           # 0.2
JustActionTime_StoryMode = 1                                 # 0.2

[P_Eve_Sword_Evade_Evade1_1]
CoolTime = 0.1                                               # 0.8

[P_Eve_Sword_LockonEvade_Evade1_1]
CoolTime = 0.1                                               # 0.8

[P_Eve_Sword_Lockon_Evade1_1]
CoolTime = 0.1                                               # 0.8

[P_Eve_Sword_Lockon_Evade2_1]
CoolTime = 0.1                                               # 0.8
JustActionTime = 1                                           # 0.15
JustActionTime_StoryMode = 1                                 # 0.3

[P_Eve_Sword_Normal_DashAttack1_1]
CoolTime = 1                                                 # 8

[P_Eve_Sword_Normal_DashAttack3_1]
CoolTime = 1                                                 # 8

[P_Eve_Sword_Normal_DashAttack4_1]
CoolTime = 1                                                 # 8

[P_Eve_Sword_Normal_Evade1_1]
CoolTime = 0.1                                               # 0.8

[P_Eve_Sword_Normal_Evade2_1]
CoolTime = 0.1                                               # 0.8
JustActionTime = 1                                           # 0.15
JustActionTime_StoryMode = 1                                 # 0.3

[P_Eve_Sword_Normal_Guard1_1]
CoolTime = 0.1                                               # 0.4

[P_Eve_Sword_Normal_Guard2_1]
CoolTime = 0.1                                               # 0.4
JustActionTime = 1                                           # 0.15
JustActionTime_StoryMode = 1                                 # 0.2

[P_Eve_Tachy_Lockon_Evade1_1]
JustActionTime = 1                                           # 0.2
JustActionTime_StoryMode = 1                                 # 0.3

[P_Eve_Tachy_Normal_Evade1_1]
JustActionTime = 1                                           # 0.2
JustActionTime_StoryMode = 1                                 # 0.3

[P_Eve_Tachy_Normal_Guard1_1]
CoolTime = 0.1                                               # 0.2
JustActionTime = 1                                           # 0.2
JustActionTime_StoryMode = 1                                 # 0.2

[P_Eve_Tachy_Start1_1]
AttackDamageRate = 50                                        # 0
Cancelable = true                                            # false
FirstActiveStepByEffect = ""                                 # "[{\"Effect\":\"P_Eve_TachyFusionModeItem\", \"SkillActiveStepAlias\":\"P_Eve_TachyFusion_Start1_Cast1\"}]"
FirstSkillActiveAlias = "P_Eve_Tachy_Start2_Cast1"           # "P_Eve_Tachy_Start1_Cast1"
ShieldAttackDamageRate = 50                                  # 0
SkillType = "SkillType_MeleeAttack"                          # "SkillType_None"
TargetDeadType = "Step2"                                     # "None"
TargetFilterAlias = "P_Eve_Tachy_Start2_1_Target"            # "P_Eve_Tachy_Start1_1_Target"
WorldObjectHitShow = "Hit/Result_Hit_Env"                    # ""

